FROM elixir:1.14.3-alpine

ENV MIX_ENV test

WORKDIR /app 

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs .
COPY mix.lock .

RUN mix deps.get && \
    mix deps.compile

COPY lib lib
COPY test test
COPY .formatter.exs .
COPY README.md .

RUN mix compile

